Metrics/LineLength:
  Max: 91
  Exclude:
    - 'spec/dummy/**/*'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'lib/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: no_space
