name: Rails integration tests

permissions: {}
on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  check-user-permission:
    runs-on: ubuntu-latest
    name: Check user permission
    steps:
      - name: Get User Permission
        id: checkAccess
        uses: actions-cool/check-user-permission@v2
        with:
          require: write
          username: ${{ github.triggering_actor }}
      - name: Check User Permission
        if: steps.checkAccess.outputs.require-result == 'false'
        env:
          trigger-actor: ${{ github.triggering_actor }}
          actor-name: ${{ github.actor }}
          permission: ${{ steps.checkAccess.outputs.user-permission }}
        run: |
          echo "${ trigger-actor } does not have permissions on this repo."
          echo "Current permission level is ${ permission }"
          echo "Job originally triggered by ${ actor-name }"
          exit 1
  set-matrix:
    runs-on: ubuntu-latest
    name: Set Rails versions
    needs:
      - check-user-permission
    outputs:
      RAILS_VERSIONS: ${{ steps.compute-outputs.outputs.RAILS_VERSIONS }}
    steps:
      # Get latest Rails versions for 6.x.x and 7.x.x
      - id: compute-outputs
        name: Compute outputs
        # fetches current Rails versions numbers > 6 and not 'beta'
        run: |
          rails_versions=$(curl https://rubygems.org/api/v1/versions/rails.json | jq '[.[] | select(.number | test("beta") | not)] | group_by(.number[:1])[] | (.[0].number) | select(.[:1]|tonumber > 6)' | jq -s -c)
          echo "RAILS_VERSIONS=$rails_versions" >> $GITHUB_OUTPUT
  set-ruby-version:
    runs-on: ubuntu-latest
    name: Set Ruby version
    needs:
      - check-user-permission
    outputs:
      RUBY_VERSION: ${{ steps.set-ruby-version.outputs.RUBY_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - id: set-ruby-version
        name: Set Ruby version
        run: |
          echo "RUBY_VERSION=$(cat .ruby-version)" >> $GITHUB_OUTPUT
  build-rails:
    strategy:
      fail-fast: false
      matrix:
        # Build containers with the latest 6.x.x and 7.x.x Rails versions
        rails: ${{ fromJSON(needs.set-matrix.outputs.RAILS_VERSIONS) }}
    runs-on: ubuntu-latest
    name: Build and cache Docker containers
    needs:
      - set-matrix
      - set-ruby-version
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and cache
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            RAILS_VERSION=${{ matrix.rails }}
            RUBY_VERSION=${{ needs.set-ruby-version.outputs.RUBY_VERSION }}
          push: false
          tags: mail-notify-integration-rails-${{ matrix.rails }}-${{ needs.set-ruby-version.outputs.RUBY_VERSION }}:latest
          outputs: type=docker, dest=/tmp/rails-${{ matrix.rails }}-${{ needs.set-ruby-version.outputs.RUBY_VERSION }}-image.tar
          cache-from: type=gha,scope=build-${{ matrix.rails }}-${{ needs.set-ruby-version.outputs.RUBY_VERSION }}
          cache-to: type=gha,mode=min,scope=build-${{ matrix.rails }}-${{ needs.set-ruby-version.outputs.RUBY_VERSION }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rails-${{ matrix.rails }}-${{ needs.set-ruby-version.outputs.RUBY_VERSION }}-image
          path: /tmp/rails-${{ matrix.rails }}-${{ needs.set-ruby-version.outputs.RUBY_VERSION }}-image.tar
  mailer-previews:
    strategy:
      fail-fast: false
      # Run against the latest 6.x.x and 7.x.x Rails versions
      matrix:
        rails: ${{ fromJSON(needs.set-matrix.outputs.RAILS_VERSIONS) }}
    env:
      MATRIX_RAILS: ${{ matrix.rails }}
      RUBY_VERSION: ${{ needs.set-ruby-version.outputs.RUBY_VERSION }}
    runs-on: ubuntu-latest
    needs:
      - set-matrix
      - set-ruby-version
      - build-rails
    steps:
      - name: Download image
        uses: actions/download-artifact@v4
        with:
          name: rails-${{ env.MATRIX_RAILS }}-${{ env.RUBY_VERSION }}-image
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/rails-${MATRIX_RAILS}-${RUBY_VERSION}-image.tar
      - name: Run integration tests
        env:
          NOTIFY_API_KEY: ${{ secrets.NOTIFY_API_KEY }}
        run: |
          docker run --rm -e "NOTIFY_API_KEY=$NOTIFY_API_KEY" \
          mail-notify-integration-rails-${MATRIX_RAILS}-${RUBY_VERSION}:latest bin/rails test:system
  sending:
    strategy:
      fail-fast: false
      # Run against the latest 5.x.x, 6.x.x and 7.x.x Rails versions
      matrix:
        rails: ${{ fromJSON(needs.set-matrix.outputs.RAILS_VERSIONS) }}
    env:
      MATRIX_RAILS: ${{ matrix.rails }}
      RUBY_VERSION: ${{ needs.set-ruby-version.outputs.RUBY_VERSION }}
    runs-on: ubuntu-latest
    needs:
      - set-matrix
      - set-ruby-version
      - build-rails
    steps:
      - name: Download image
        uses: actions/download-artifact@v4
        with:
          name: rails-${{ env.MATRIX_RAILS }}-${{ env.RUBY_VERSION }}-image
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/rails-${MATRIX_RAILS}-${RUBY_VERSION}-image.tar
      - name: Run integration tests
        env:
          NOTIFY_API_KEY: ${{ secrets.NOTIFY_API_KEY }}
        run: |
          docker run --rm -e "NOTIFY_API_KEY=$NOTIFY_API_KEY" \
          mail-notify-integration-rails-${MATRIX_RAILS }-${RUBY_VERSION}:latest bin/rails test
  results:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: All integration tests
    needs:
      - mailer-previews
      - sending
    steps:
      # If any of the previous actions failed, we return a non-zero exit code
      - run: exit 1
        if: >-
          ${{
               contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
            || contains(needs.*.result, 'skipped')
          }}
      - run: echo "integration tests passed"
